name: Code Convention Check

on:
  pull_request:
    branches:
      - '**'  # 모든 브랜치에서 pull request 발생 시 실행

jobs:
  check-code-style:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Gradle을 사용해 코드 스타일 검사
      - name: Check code style with Spotless
        run: ./gradlew spotlessCheck --no-daemon
